
// Generated by https://quicktype.io
// Para crear esto primero hacer un COPY a la data de la API, y luego presionar Ctrl+shift+V y especificar el nombre de la interface
export interface PokeResponse {
    count:    number;
    next:     string;
    previous: null;
    results:  Result[];
}

export interface Result {
    name: string;
    url:  string;
}
